### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'columns'

### ISSUE THREAD

**Issue by pbebbo** [chasedehan/BoostARoota#14]
When running br.fit(train.values,labels.values) I get the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-40b3062deeb7> in <module>()
      1 br = BoostARoota(metric='logloss')
      2 
----> 3 br.fit(train.values,labels.values)
      4 len(train.columns)
      5 len(br.keep_vars_)

~/anaconda2/envs/py3k/lib/python3.6/site-packages/boostaroota/boostaroota.py in fit(self, x, y)
     51                                        max_rounds=self.max_rounds,
     52                                        delta=self.delta,
---> 53                                        silent=self.silent)
     54         return self
     55 

~/anaconda2/envs/py3k/lib/python3.6/site-packages/boostaroota/boostaroota.py in _BoostARoota(x, y, metric, clf, cutoff, iters, max_rounds, delta, silent)
    224                                                n_iterations=iters,
    225                                                delta=delta,
--> 226                                                silent=silent)
    227         else:
    228             crit, keep_vars = _reduce_vars_sklearn(new_x,

~/anaconda2/envs/py3k/lib/python3.6/site-packages/boostaroota/boostaroota.py in _reduce_vars_xgb(x, y, metric, this_round, cutoff, n_iterations, delta, silent)
    113     for i in range(1, n_iterations+1):
    114         # Create the shadow variables and run the model to obtain importances
--> 115         new_x, shadow_names = _create_shadow(x)
    116         dtrain = xgb.DMatrix(new_x, label=y)
    117         bst = xgb.train(param, dtrain, verbose_eval=False)

~/anaconda2/envs/py3k/lib/python3.6/site-packages/boostaroota/boostaroota.py in _create_shadow(x_train)
     77     """
     78     x_shadow = x_train.copy()
---> 79     for c in x_shadow.columns:
     80         np.random.shuffle(x_shadow[c].values)
     81     # rename the shadow

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

**Comment by chasedehan** [comment]
You able to provide a snippet of code so I can see what you are doing?

Are you passing in a 2d numpy array?  If so, that would be why it is breaking - BoostARoota requires data to be passed in as a Pandas Dataframe.

**Comment by chasedehan** [comment]
I am going to close this, please let me know if you still have an issue.
