### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by pbebbo** [chasedehan/BoostARoota#15]
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-23-0a6e9af35e76> in <module>()
      1 br = BoostARoota(metric='logloss',delta=0.05)
----> 2 br.fit(all_feats,target_data);

~/anaconda2/envs/py3k/lib/python3.6/site-packages/boostaroota/boostaroota.py in fit(self, x, y)
     51                                        max_rounds=self.max_rounds,
     52                                        delta=self.delta,
---> 53                                        silent=self.silent)
     54         return self
     55 

~/anaconda2/envs/py3k/lib/python3.6/site-packages/boostaroota/boostaroota.py in _BoostARoota(x, y, metric, clf, cutoff, iters, max_rounds, delta, silent)
    224                                                n_iterations=iters,
    225                                                delta=delta,
--> 226                                                silent=silent)
    227         else:
    228             crit, keep_vars = _reduce_vars_sklearn(new_x,

~/anaconda2/envs/py3k/lib/python3.6/site-packages/boostaroota/boostaroota.py in _reduce_vars_xgb(x, y, metric, this_round, cutoff, n_iterations, delta, silent)
    139     #Check for the stopping criteria
    140     #Basically looking to make sure we are removing at least 10% of the variables, or we should stop
--> 141     if (len(real_vars['feature']) / len(x.columns)) > (1-delta):
    142         criteria = True
    143     else:

ZeroDivisionError: division by zero

**Comment by chasedehan** [comment]
Please see this issue:
https://github.com/chasedehan/BoostARoota/issues/9

Looks like you need to limit the number of rounds that the model goes through or adjust criteria to cut out less.  Basically, it is removing every feature.

I'm going to close this, please open another issue if it persists or reach out to me directly.

**Comment by pbebbo** [comment]
The issue went away when I converted the target (categorical) in to a set of dummy vars



On 17 Apr 2018, at 11:41, Chase DeHan <notifications@github.com<mailto:notifications@github.com>> wrote:


Please see this issue:
#9<https://github.com/chasedehan/BoostARoota/issues/9>

Looks like you need to limit the number of rounds that the model goes through or adjust criteria to cut out less. Basically, it is removing every feature.

I'm going to close this, please open another issue if it persists or reach out to me directly.

**Comment by chasedehan** [comment]
Ahh, in your code you passed in 'logloss' as the metric.  If you have a multiclass target, the only metric that will be accepted is 'mlogloss'.

**Comment by pbebbo** [comment]
Doh, thank you!

On 17 Apr 2018, at 14:01, Chase DeHan <notifications@github.com<mailto:notifications@github.com>> wrote:

mlogloss
