### ISSUE TITLE
How do I cite BoostARoota?

### ISSUE THREAD

**Issue by bbb801** [chasedehan/BoostARoota#18]
Dear author,

How do I cite BoostARoota? Is there a paper on it? Thanks.

Regards,
Jundong

**Comment by chasedehan** [comment]
Jundong,

Unfortunately, there isn't a written paper on the algorithm itself.  I
would recommend just linking to the github repo.  I am the author if you
need to cite an author.

I appreciate you looking into the algorithm and hope it was helpful for
your research.  I would be interested in your research.

Thanks,
Chase
